In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r'C:\Users\APT\Downloads\ML\spamemail.csv')

In [3]:
df

Unnamed: 0 label                                               text  \
0            605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1           2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2           3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3           4685  spam  Subject: photoshop , windows , office . cheap ...   
4           2030   ham  Subject: re : indian springs\r\nthis deal is t...   
...          ...   ...                                                ...   
5166        1518   ham  Subject: put the 10 on the ft\r\nthe transport...   
5167         404   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...   
5168        2933   ham  Subject: calpine daily gas nomination\r\n>\r\n...   
5169        1409   ham  Subject: industrial worksheets for august 2000...   
5170        4807  spam  Subject: important online banking alert\r\ndea...   

      label_num  
0             0  
1             0  
2             0  
3             1  
4             0  
...         ...  
5166          0  
5167          0  
5168          0  
5169          0  
5170          1  

[5171 rows x 4 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [7]:
df.groupby('label').describe()

Unnamed: 0                                                         \
           count    mean          std     min      25%     50%      75%   
label                                                                     
ham       3672.0  1835.5  1060.159422     0.0   917.75  1835.5  2753.25   
spam      1499.0  4421.0   432.868340  3672.0  4046.50  4421.0  4795.50   

              label_num                                     
          max     count mean  std  min  25%  50%  75%  max  
label                                                       
ham    3671.0    3672.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
spam   5170.0    1499.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

In [8]:
df['spam']=df['label'].apply(lambda x:1 if x=='spam' else 0)

In [9]:
df

Unnamed: 0 label                                               text  \
0            605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1           2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2           3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3           4685  spam  Subject: photoshop , windows , office . cheap ...   
4           2030   ham  Subject: re : indian springs\r\nthis deal is t...   
...          ...   ...                                                ...   
5166        1518   ham  Subject: put the 10 on the ft\r\nthe transport...   
5167         404   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...   
5168        2933   ham  Subject: calpine daily gas nomination\r\n>\r\n...   
5169        1409   ham  Subject: industrial worksheets for august 2000...   
5170        4807  spam  Subject: important online banking alert\r\ndea...   

      label_num  spam  
0             0     0  
1             0     0  
2             0     0  
3             1     1  
4             0     0  
...         ...   ...  
5166          0     0  
5167          0     0  
5168          0     0  
5169          0     0  
5170          1     1  

[5171 rows x 5 columns]

In [10]:
df.drop(['label','label_num'],axis=1,inplace=True)

In [12]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [13]:
df

text  spam
0     Subject: enron methanol ; meter # : 988291\r\n...     0
1     Subject: hpl nom for january 9 , 2001\r\n( see...     0
2     Subject: neon retreat\r\nho ho ho , we ' re ar...     0
3     Subject: photoshop , windows , office . cheap ...     1
4     Subject: re : indian springs\r\nthis deal is t...     0
...                                                 ...   ...
5166  Subject: put the 10 on the ft\r\nthe transport...     0
5167  Subject: 3 / 4 / 2000 and following noms\r\nhp...     0
5168  Subject: calpine daily gas nomination\r\n>\r\n...     0
5169  Subject: industrial worksheets for august 2000...     0
5170  Subject: important online banking alert\r\ndea...     1

[5171 rows x 2 columns]

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_tes=train_test_split(df.text,df.spam,test_size=0.25)

In [16]:
#for converting every word into vector count

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
v=CountVectorizer()

In [22]:
x_train_count=v.fit_transform(x_train.values)
import numpy as np

In [24]:
x_train_count.toarray()

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 7,  0,  0, ...,  0,  0,  0],
       [35,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]], dtype=int64)

In [26]:
from sklearn.naive_bayes import MultinomialNB

In [27]:
model=MultinomialNB()

In [28]:
model.fit(x_train_count,y_train)

MultinomialNB()

In [29]:
x_test_count=v.transform(x_test)

In [31]:
model.score(x_test_count,y_tes)

0.9775715390564579

In [42]:
emails=["hey abhimanyu how are you i m karishma i love you","20 discount on sales offer ends soon cheap online offer"]

In [43]:
emails_count=v.transform(emails)

In [44]:
model.predict(emails_count)

array([0, 1], dtype=int64)

In [54]:
email=["register and get 20% cheap discount ","hello abhimanyu can we have dinner togethar"]

In [55]:
email_count=v.transform(email)

In [56]:
model.predict(email_count)

array([1, 0], dtype=int64)